VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "AreaDef"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'--------------------------------------------
' Class Module: AreaDef
'--------------------------------------------
Public Row As Long
Public workload As Double
Public width As Double
Public height As Double
Public Name As String

'--- ADD THESE TWO LINES ---
Public centerX As Double
Public centerY As Double
'---------------------------
