VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "RectangleDef"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'--------------------------------------------
' Class Module: RectangleDef
'--------------------------------------------
Public Left As Double
Public Right As Double
Public Bottom As Double
Public Top As Double

'--- ADD THESE TWO LINES ---
Public centerX As Double
Public centerY As Double
'---------------------------

Public AreaName As String
