VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ZoneDef"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'--------------------------------------------
' Class Module: ZoneDef
'--------------------------------------------
Public Left As Double
Public Right As Double
Public Bottom As Double
Public Top As Double
Public Name As String

'--- ADD THESE TWO LINES ---
Public centerX As Double
Public centerY As Double
'---------------------------
