VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ZoneDef"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'--------------------------------------------
' Class Module: ZoneDef
' Description: Represents a placement zone where areas can be located.
'--------------------------------------------
Option Explicit

Public Name As String
Public Left As Double
Public Right As Double
Public Bottom As Double
Public Top As Double
Public centerX As Double
Public centerY As Double
